const $ = id => document.getElementById(id);
let api, profile;
let classes = [];
let rows = [];
let selectedClass = null;

function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function formatRole(r){return (r||"-").replaceAll("_"," ")}
function localDateID(){return new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date())}
function localISODate(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return `${o.year}-${o.month}-${o.day}`}
function routeFor(code){return {DASHBOARD:"dashboard.html",ADMINISTRASI_KEPALA:"administrasi.html",DATA_SISWA:"siswa.html",DATA_GURU:"guru.html",KELAS:"kelas.html",MATA_PELAJARAN:"mapel.html",JADWAL:"jadwal.html",ABSENSI_GURU:"absensi-guru.html",ABSENSI_SISWA:"absensi-siswa.html"}[code]||"#"}
function statusLabel(s){return {BELUM_DIABSEN:"Belum Diabsen",HADIR:"Hadir",TERLAMBAT:"Terlambat",IZIN:"Izin",SAKIT:"Sakit",ALFA:"Alfa"}[s]||s}
function statusOptions(current){return ["BELUM_DIABSEN","HADIR","TERLAMBAT","IZIN","SAKIT","ALFA"].map(s=>`<option value="${s}" ${s===current?"selected":""}>${statusLabel(s)}</option>`).join("")}

async function loadProfile(user){const r=await api.db.select("profiles",`select=id,full_name,role,is_active&id=eq.${encodeURIComponent(user.id)}&limit=1`);if(!r?.[0])throw new Error("Profil pengguna tidak ditemukan.");if(!r[0].is_active)throw new Error("Akun SIMANIS tidak aktif.");return r[0]}
async function loadMenu(){const m=await api.db.rpc("get_my_modules",{});$("sidebarMenu").innerHTML=(m||[]).map(x=>`<a href="${routeFor(x.code)}" class="nav-item ${x.code==="ABSENSI_SISWA"?"active":""}"><span class="nav-dot"></span><span>${esc(x.name)}</span></a>`).join("");document.querySelectorAll('.nav-item[href="#"]').forEach(a=>a.addEventListener("click",e=>{e.preventDefault();alert(`Modul "${a.textContent.trim()}" akan diaktifkan bertahap.`)}))}

async function loadClasses(){classes=await api.db.rpc("get_my_attendance_classes",{})||[];$("classFilter").innerHTML='<option value="">Pilih Kelas...</option>'+classes.map(c=>`<option value="${c.class_id}">${esc(c.class_name)} · ${c.student_count} siswa${c.can_manage?"":" · lihat saja"}</option>`).join("");if(classes.length){$("classFilter").value=classes[0].class_id;await chooseClass(classes[0].class_id)}else{selectedClass=null;rows=[];renderAll();$("classInfo").innerHTML='<div><strong>Tidak ada kelas yang dapat diakses.</strong><br><span>Hubungi administrator jika akun seharusnya memiliki akses.</span></div>'}}

async function chooseClass(id){selectedClass=classes.find(c=>c.class_id===id)||null;if(!selectedClass){rows=[];renderAll();return}await loadAttendance()}
async function loadAttendance(){if(!selectedClass)return;const d=$("attendanceDate").value;$("saveInfo").textContent="Memuat data absensi...";rows=await api.db.rpc("get_class_attendance_by_date",{p_class_id:selectedClass.class_id,p_date:d})||[];renderAll()}

function filteredRows(){const q=$("searchInput").value.trim().toLowerCase();const st=$("statusFilter").value;return rows.filter(r=>{const hay=`${r.full_name||""} ${r.nis||""} ${r.nisn||""}`.toLowerCase();return (!q||hay.includes(q))&&(!st||r.attendance_status===st)})}
function renderStats(){const total=rows.length;const present=rows.filter(r=>["HADIR","TERLAMBAT"].includes(r.attendance_status)).length;const excused=rows.filter(r=>["IZIN","SAKIT"].includes(r.attendance_status)).length;const missing=rows.filter(r=>["ALFA","BELUM_DIABSEN"].includes(r.attendance_status)).length;$("statTotal").textContent=total;$("statPresent").textContent=present;$("statExcused").textContent=excused;$("statMissing").textContent=missing}
function renderClassInfo(){if(!selectedClass){$("classInfo").innerHTML='<div><strong>Pilih kelas untuk mulai absensi</strong><br><span>Daftar kelas menyesuaikan hak akses akun.</span></div>';return}$("classInfo").innerHTML=`<div><strong>${esc(selectedClass.class_name)}</strong><br><span>Wali kelas: ${esc(selectedClass.homeroom_teacher||"Belum ditentukan")} · ${selectedClass.student_count} siswa · ${selectedClass.can_manage?"Dapat mengelola":"Mode lihat saja"}</span></div><span>${esc($("attendanceDate").value)}</span>`}
function rowControls(r){const disabled=selectedClass?.can_manage?"":"disabled";const status=r.attendance_status||"BELUM_DIABSEN";return `<select data-field="status" data-id="${r.enrollment_id}" ${disabled}>${statusOptions(status)}</select>`}
function renderTable(){const data=filteredRows();if(!data.length){$("attendanceBody").innerHTML='<tr><td colspan="7"><div class="empty-state">Tidak ada siswa yang cocok.</div></td></tr>';$("attendanceCards").innerHTML='<div class="empty-state">Tidak ada siswa yang cocok.</div>';return}const disabled=selectedClass?.can_manage?"":"disabled";$("attendanceBody").innerHTML=data.map((r,i)=>`<tr><td>${r.roll_number??i+1}</td><td><div class="student-name">${esc(r.full_name)}</div><div class="student-sub">NIS ${esc(r.nis||"-")} · NISN ${esc(r.nisn||"-")}</div></td><td>${esc(r.gender||"-")}</td><td>${rowControls(r)}<div style="margin-top:4px"><span class="st-badge st-${r.attendance_status}">${statusLabel(r.attendance_status)}</span></div></td><td><input data-field="arrival" data-id="${r.enrollment_id}" type="time" value="${esc(r.arrival_time||"")}" ${disabled}></td><td><input data-field="late" data-id="${r.enrollment_id}" type="number" min="0" value="${Number(r.late_minutes||0)}" style="width:70px" ${disabled}></td><td><input data-field="note" data-id="${r.enrollment_id}" type="text" value="${esc(r.note||"")}" placeholder="Catatan" ${disabled}></td></tr>`).join("");$("attendanceCards").innerHTML=data.map((r,i)=>`<article class="student-att-card"><div class="top"><div><h4>${esc(r.full_name)}</h4><p>No. ${r.roll_number??i+1} · NIS ${esc(r.nis||"-")}</p></div><span class="st-badge st-${r.attendance_status}">${statusLabel(r.attendance_status)}</span></div><div class="fields"><label><span>Status</span>${rowControls(r)}</label><label><span>Jam Datang</span><input data-field="arrival" data-id="${r.enrollment_id}" type="time" value="${esc(r.arrival_time||"")}" ${disabled}></label><label><span>Terlambat (menit)</span><input data-field="late" data-id="${r.enrollment_id}" type="number" min="0" value="${Number(r.late_minutes||0)}" ${disabled}></label><label class="full"><span>Catatan</span><input data-field="note" data-id="${r.enrollment_id}" type="text" value="${esc(r.note||"")}" ${disabled}></label></div></article>`).join("");bindRowInputs()}
function bindRowInputs(){document.querySelectorAll("[data-field]").forEach(el=>{const evt=el.tagName==="SELECT"?"change":"input";el.addEventListener(evt,()=>{const r=rows.find(x=>x.enrollment_id===el.dataset.id);if(!r)return;const f=el.dataset.field;if(f==="status"){r.attendance_status=el.value;if(!["HADIR","TERLAMBAT"].includes(el.value))r.arrival_time=null;if(el.value!=="TERLAMBAT")r.late_minutes=0;renderStats();renderTable()}else if(f==="arrival")r.arrival_time=el.value||null;else if(f==="late")r.late_minutes=Math.max(0,Number(el.value||0));else if(f==="note")r.note=el.value||null;updateSaveInfo()})})}
function updateSaveInfo(){if(!selectedClass){$("saveInfo").textContent="Belum ada kelas dipilih.";return}const marked=rows.filter(r=>r.attendance_status!=="BELUM_DIABSEN").length;$("saveInfo").textContent=`${selectedClass.class_name} · ${marked}/${rows.length} siswa memiliki status · ${selectedClass.can_manage?"siap disimpan":"mode lihat saja"}`;const disabled=!selectedClass.can_manage;$("saveBtn").disabled=disabled;$("markAllPresent").disabled=disabled;$("markEmptyPresent").disabled=disabled;$("markEmptyAbsent").disabled=disabled}
function renderAll(){renderStats();renderClassInfo();renderTable();updateSaveInfo()}

function markRows(mode){if(!selectedClass?.can_manage)return;rows.forEach(r=>{if(mode==="ALL_PRESENT"||r.attendance_status==="BELUM_DIABSEN"){r.attendance_status=mode==="EMPTY_ABSENT"?"ALFA":"HADIR";r.late_minutes=0;if(r.attendance_status!=="HADIR")r.arrival_time=null}});renderAll()}

async function saveAttendance(){if(!selectedClass?.can_manage)return;const items=rows.filter(r=>r.attendance_status!=="BELUM_DIABSEN").map(r=>({enrollment_id:r.enrollment_id,status:r.attendance_status,arrival_time:r.arrival_time||null,late_minutes:Number(r.late_minutes||0),note:r.note||null}));if(!items.length){alert("Belum ada status absensi yang dipilih.");return}const btn=$("saveBtn");btn.disabled=true;btn.textContent="Menyimpan...";try{const count=await api.db.rpc("save_class_student_attendance",{p_class_id:selectedClass.class_id,p_date:$("attendanceDate").value,p_items:items});await loadAttendance();alert(`${count} data absensi berhasil disimpan.`)}catch(err){alert("Gagal menyimpan absensi: "+(err.message||err))}finally{btn.textContent="Simpan Absensi";updateSaveInfo()}}

$("attendanceDate").value=localISODate();
$("classFilter").addEventListener("change",()=>chooseClass($("classFilter").value));
$("attendanceDate").addEventListener("change",()=>loadAttendance());
$("searchInput").addEventListener("input",renderTable);
$("statusFilter").addEventListener("change",renderTable);
$("markAllPresent").addEventListener("click",()=>markRows("ALL_PRESENT"));
$("markEmptyPresent").addEventListener("click",()=>markRows("EMPTY_PRESENT"));
$("markEmptyAbsent").addEventListener("click",()=>markRows("EMPTY_ABSENT"));
$("reloadBtn").addEventListener("click",()=>loadAttendance());
$("saveBtn").addEventListener("click",saveAttendance);

(async function boot(){try{api=await window.simanisReady;const session=await api.auth.getSession();if(!session){location.replace("index.html");return}const user=await api.auth.getUser();if(!user){location.replace("index.html");return}profile=await loadProfile(user);$("sideUserName").textContent=profile.full_name||user.email||"Pengguna";$("sideUserRole").textContent=formatRole(profile.role);$("headerUser").textContent=profile.full_name||user.email||"Pengguna";$("currentDate").textContent=localDateID();await loadMenu();await loadClasses();$("logoutBtn").addEventListener("click",async()=>{await api.auth.signOut();location.replace("index.html")})}catch(err){console.error(err);alert("Absensi Siswa gagal dimuat: "+(err.message||err))}finally{$("loading")?.classList.add("hidden")}})();
