const $ = id => document.getElementById(id);
let api, profile, rows = [];
const ADMIN_ROLES = ["SUPER_ADMIN","TU","WAKA_KURIKULUM"];

function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function formatRole(r){return (r||"-").replaceAll("_"," ")}
function localDateID(){return new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date())}
function todayYMD(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return `${o.year}-${o.month}-${o.day}`}
function formatTime(ts){if(!ts)return "-";return new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(ts))}
function routeFor(code){return {DASHBOARD:"dashboard.html",ADMINISTRASI_KEPALA:"administrasi.html",DATA_SISWA:"siswa.html",DATA_GURU:"guru.html",KELAS:"kelas.html",MATA_PELAJARAN:"mapel.html",JADWAL:"jadwal.html",ABSENSI_GURU:"absensi-guru.html"}[code]||"#"}
function statusLabel(s){return {HADIR:"Hadir",TERLAMBAT:"Terlambat",IZIN:"Izin",SAKIT:"Sakit",DINAS:"Dinas",ALFA:"Alfa",BELUM_ABSEN:"Belum Absen",TIDAK_ADA_JADWAL:"Tidak Ada Jadwal"}[s]||s}
function isAdmin(){return ADMIN_ROLES.includes(profile?.role)}

async function loadProfile(user){const r=await api.db.select("profiles",`select=id,full_name,role,is_active,teacher_id&id=eq.${encodeURIComponent(user.id)}&limit=1`);if(!r?.[0])throw new Error("Profil pengguna tidak ditemukan.");if(!r[0].is_active)throw new Error("Akun tidak aktif.");return r[0]}

async function loadMenu(){const m=await api.db.rpc("get_my_modules",{});$("sidebarMenu").innerHTML=(m||[]).map(x=>`<a href="${routeFor(x.code)}" class="nav-item ${x.code==="ABSENSI_GURU"?"active":""}"><span class="nav-dot"></span><span>${esc(x.name)}</span></a>`).join("");document.querySelectorAll('.nav-item[href="#"]').forEach(a=>a.onclick=e=>{e.preventDefault();alert(`Modul "${a.textContent.trim()}" akan diaktifkan bertahap.`)})}

async function loadAttendance(){const d=$("attendanceDate").value;rows=await api.db.rpc("get_teacher_attendance_by_date",{p_date:d})||[];if(["GURU","WALI_KELAS"].includes(profile.role)&&profile.teacher_id){rows=rows.filter(r=>r.teacher_id===profile.teacher_id);$("scheduleFilter").value="ALL";$("scheduleFilter").disabled=true}
renderStats();render();$("dateCaption").textContent=`Data absensi tanggal ${new Intl.DateTimeFormat("id-ID",{dateStyle:"full",timeZone:"Asia/Jakarta"}).format(new Date(d+"T12:00:00+07:00"))}`}

function renderStats(){const scheduled=rows.filter(r=>r.has_schedule);$("statScheduled").textContent=scheduled.length;$("statPresent").textContent=scheduled.filter(r=>["HADIR","TERLAMBAT"].includes(r.attendance_status)).length;$("statExcused").textContent=scheduled.filter(r=>["IZIN","SAKIT","DINAS"].includes(r.attendance_status)).length;$("statMissing").textContent=scheduled.filter(r=>["BELUM_ABSEN","ALFA"].includes(r.attendance_status)).length}

function filtered(){const q=$("searchInput").value.trim().toLowerCase(),sf=$("scheduleFilter").value,st=$("statusFilter").value;return rows.filter(r=>{const hay=`${r.teacher_code??""} ${r.teacher_name||""} ${r.schedule_detail||""}`.toLowerCase();return(!q||hay.includes(q))&&(sf==="ALL"||(sf==="SCHEDULED"&&r.has_schedule)||(sf==="NONE"&&!r.has_schedule))&&(!st||r.attendance_status===st)})}

function actionHtml(r){const today=$("attendanceDate").value===todayYMD();let out=[];if(today&&r.has_schedule){if(r.attendance_status==="BELUM_ABSEN")out.push(`<button class="primary" data-checkin="${r.teacher_id}">Check In</button>`);if(["HADIR","TERLAMBAT"].includes(r.attendance_status)&&r.check_in&&!r.check_out)out.push(`<button class="primary" data-checkout="${r.teacher_id}">Check Out</button>`)}if(isAdmin())out.push(`<button data-manage="${r.teacher_id}">Kelola</button>`);return out.join("")||"-"}

function render(){const list=filtered();if(!list.length){$("attendanceBody").innerHTML='<tr><td colspan="9"><div class="empty-state">Tidak ada data yang cocok.</div></td></tr>';$("attendanceCards").innerHTML='<div class="empty-state">Tidak ada data yang cocok.</div>';return}
$("attendanceBody").innerHTML=list.map(r=>`<tr><td>${esc(r.teacher_code??"-")}</td><td><div class="att-name">${esc(r.teacher_name)}</div></td><td>${r.has_schedule?`<b>${String(r.scheduled_start).slice(0,5)}–${String(r.scheduled_end).slice(0,5)}</b><div class="muted-small">${esc(r.schedule_detail||"")}</div>`:"-"}</td><td><span class="att-status st-${r.attendance_status}">${statusLabel(r.attendance_status)}</span></td><td>${formatTime(r.check_in)}</td><td>${formatTime(r.check_out)}</td><td>${Number(r.late_minutes||0)>0?`${r.late_minutes} menit`:'-'}</td><td>${esc(r.note||"-")}</td><td><div class="att-actions">${actionHtml(r)}</div></td></tr>`).join("");
$("attendanceCards").innerHTML=list.map(r=>`<article class="att-card"><div class="att-card-head"><div><h4>${esc(r.teacher_name)}</h4><p>Kode ${esc(r.teacher_code??"-")} · ${r.has_schedule?`${String(r.scheduled_start).slice(0,5)}–${String(r.scheduled_end).slice(0,5)}`:"Tidak ada jadwal"}</p></div><span class="att-status st-${r.attendance_status}">${statusLabel(r.attendance_status)}</span></div><div class="att-card-grid"><div><b>Masuk</b><br>${formatTime(r.check_in)}</div><div><b>Pulang</b><br>${formatTime(r.check_out)}</div><div><b>Slot</b><br>${r.teaching_slots||0}</div><div><b>Terlambat</b><br>${r.late_minutes||0} menit</div></div>${r.schedule_detail?`<div class="attendance-note">${esc(r.schedule_detail)}</div>`:""}${r.note?`<div class="attendance-note"><b>Catatan:</b> ${esc(r.note)}</div>`:""}<div class="att-actions" style="margin-top:10px">${actionHtml(r)}</div></article>`).join("");
wireActions()}

function wireActions(){document.querySelectorAll("[data-checkin]").forEach(b=>b.onclick=()=>checkIn(b.dataset.checkin));document.querySelectorAll("[data-checkout]").forEach(b=>b.onclick=()=>checkOut(b.dataset.checkout));document.querySelectorAll("[data-manage]").forEach(b=>b.onclick=()=>openManage(b.dataset.manage))}

async function checkIn(id){try{await api.db.rpc("teacher_check_in",{p_teacher_id:id,p_method:isAdmin()?"ADMIN":"MANUAL",p_note:null});await loadAttendance()}catch(e){alert("Check-in gagal: "+e.message)}}
async function checkOut(id){try{await api.db.rpc("teacher_check_out",{p_teacher_id:id,p_method:isAdmin()?"ADMIN":"MANUAL",p_note:null});await loadAttendance()}catch(e){alert("Check-out gagal: "+e.message)}}

function openManage(id){const r=rows.find(x=>x.teacher_id===id);if(!r)return;$("teacherId").value=id;$("modalDate").value=$("attendanceDate").value;$("teacherInfo").textContent=`${r.teacher_name} · ${r.has_schedule?`Jadwal ${String(r.scheduled_start).slice(0,5)}–${String(r.scheduled_end).slice(0,5)}`:"Tidak ada jadwal mengajar"}`;$("attendanceStatus").value=["BELUM_ABSEN","TIDAK_ADA_JADWAL"].includes(r.attendance_status)?(r.has_schedule?"HADIR":"DINAS"):r.attendance_status;$("checkInTime").value=r.check_in?formatTime(r.check_in).replace('.',':'):"";$("checkOutTime").value=r.check_out?formatTime(r.check_out).replace('.',':'):"";$("attendanceNote").value=r.note||"";$("formMessage").textContent="";toggleTimeFields();$("attendanceModal").classList.remove("hidden")}
function closeModal(){$("attendanceModal").classList.add("hidden")}
function toggleTimeFields(){const noTime=["IZIN","SAKIT","DINAS","ALFA"].includes($("attendanceStatus").value);$("checkInTime").disabled=noTime;$("checkOutTime").disabled=noTime;if(noTime){$("checkInTime").value="";$("checkOutTime").value=""}}

async function saveAttendance(e){e.preventDefault();const btn=$("saveBtn");btn.disabled=true;btn.textContent="Menyimpan...";try{await api.db.rpc("save_teacher_attendance_admin",{p_teacher_id:$("teacherId").value,p_date:$("modalDate").value,p_status:$("attendanceStatus").value,p_note:$("attendanceNote").value.trim()||null,p_check_in_time:$("checkInTime").value||null,p_check_out_time:$("checkOutTime").value||null});closeModal();await loadAttendance()}catch(err){$("formMessage").textContent="Gagal menyimpan: "+err.message}finally{btn.disabled=false;btn.textContent="Simpan"}}
async function clearAttendance(){if(!confirm("Hapus catatan absensi guru ini?"))return;try{const ok=await api.db.rpc("clear_teacher_attendance_admin",{p_teacher_id:$("teacherId").value,p_date:$("modalDate").value});closeModal();await loadAttendance();if(!ok)alert("Tidak ada catatan tersimpan yang perlu dihapus.")}catch(e){alert("Gagal menghapus: "+e.message)}}

$("attendanceDate").value=todayYMD();
$("attendanceDate").onchange=loadAttendance;$("searchInput").oninput=render;$("scheduleFilter").onchange=render;$("statusFilter").onchange=render;$("attendanceStatus").onchange=toggleTimeFields;$("closeModalBtn").onclick=closeModal;$("cancelBtn").onclick=closeModal;$("attendanceForm").onsubmit=saveAttendance;$("clearBtn").onclick=clearAttendance;$("attendanceModal").onclick=e=>{if(e.target===$("attendanceModal"))closeModal()};

(async function boot(){try{api=await window.simanisReady;const session=await api.auth.getSession();if(!session){location.replace("index.html");return}const user=await api.auth.getUser();if(!user){location.replace("index.html");return}profile=await loadProfile(user);$("sideUserName").textContent=profile.full_name||user.email||"Pengguna";$("sideUserRole").textContent=formatRole(profile.role);$("headerUser").textContent=profile.full_name||user.email||"Pengguna";$("currentDate").textContent=localDateID();if(!isAdmin()){$("clearBtn").classList.add("hidden")}await loadMenu();await loadAttendance();$("logoutBtn").onclick=async()=>{await api.auth.signOut();location.replace("index.html")}}catch(err){console.error(err);alert("Absensi Guru gagal dimuat: "+(err.message||err))}finally{$("loading").classList.add("hidden")}})();
