const $ = (id) => document.getElementById(id);
let api, profile;
let teachers = [];
let page = 1;
const pageSize = 25;
function esc(s){return String(s ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function formatRole(role){ return (role || "-").replaceAll("_"," "); }
function localDateID(){return new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());}
function routeFor(code){if(code==="DASHBOARD") return "dashboard.html";if(code==="ADMINISTRASI_KEPALA") return "administrasi.html";if(code==="DATA_SISWA") return "siswa.html";if(code==="DATA_GURU") return "guru.html";if(code==="KELAS") return "kelas.html";return "#";}
function dayOrder(day){return {SENIN:1,SELASA:2,RABU:3,KAMIS:4,SABTU:5,AHAD:6}[day] || 99;}
async function loadProfile(user){const rows=await api.db.select("profiles",`select=id,full_name,role,is_active&id=eq.${encodeURIComponent(user.id)}&limit=1`);const p=rows?.[0];if(!p) throw new Error("Profil pengguna tidak ditemukan.");if(!p.is_active) throw new Error("Akun SIMANIS tidak aktif.");return p;}
async function loadMenu(){const modules=await api.db.rpc("get_my_modules",{});$("sidebarMenu").innerHTML=(modules||[]).map(m=>`<a href="${routeFor(m.code)}" class="nav-item ${m.code==="DATA_GURU"?"active":""}"><span class="nav-dot"></span><span>${esc(m.name)}</span></a>`).join("");document.querySelectorAll('.nav-item[href="#"]').forEach(a=>a.addEventListener("click",e=>{e.preventDefault();alert(`Modul "${a.textContent.trim()}" akan diaktifkan bertahap.`);}));}
async function loadTeachers(){teachers=await api.db.select("v_teachers_detail","select=*&order=teacher_code.asc.nullslast,full_name.asc") || [];renderStats();page=1;render();}
function getFiltered(){const q=$("searchInput").value.trim().toLowerCase();const st=$("statusFilter").value;const wf=$("workloadFilter").value;return teachers.filter(t=>{const hay=`${t.teacher_code ?? ""} ${t.full_name||""} ${t.nip||""} ${t.nuptk||""} ${t.email||""}`.toLowerCase();const okQ=!q || hay.includes(q);const okStatus=st==="SEMUA" || (st==="AKTIF" && t.is_active) || (st==="NONAKTIF" && !t.is_active);const slots=Number(t.teaching_slots_per_week||0);const okWork=!wf || (wf==="HAS" && slots>0) || (wf==="NONE" && slots===0) || (wf==="HOMEROOM" && !!t.homeroom_classes);return okQ && okStatus && okWork;});}
function renderStats(){const active=teachers.filter(t=>t.is_active);$("statActive").textContent=active.length;$("statHomeroom").textContent=active.filter(t=>t.homeroom_classes).length;$("statNoSchedule").textContent=active.filter(t=>Number(t.teaching_slots_per_week||0)===0).length;$("statSlots").textContent=active.reduce((n,t)=>n+Number(t.teaching_slots_per_week||0),0);}
function render(){const rows=getFiltered();const pages=Math.max(1,Math.ceil(rows.length/pageSize));if(page>pages) page=pages;const start=(page-1)*pageSize;const slice=rows.slice(start,start+pageSize);if(!slice.length){$("teacherTableBody").innerHTML='<tr><td colspan="7"><div class="empty-state">Tidak ada guru yang cocok.</div></td></tr>';$("teacherCards").innerHTML='<div class="empty-state">Tidak ada guru yang cocok.</div>';}else{$("teacherTableBody").innerHTML=slice.map(t=>`<tr><td>${esc(t.teacher_code ?? "-")}</td><td><div class="teacher-name">${esc(t.full_name)}</div><div class="muted">${esc(t.employment_status || "Status kepegawaian belum diisi")}</div></td><td><div>${esc(t.nip || "-")}</div><div class="muted">${esc(t.nuptk || "-")}</div></td><td><div>${esc(t.phone || "-")}</div><div class="muted">${esc(t.email || "-")}</div></td><td><span class="workload-pill">${Number(t.teaching_slots_per_week||0)} slot/minggu</span></td><td>${t.homeroom_classes?`<span class="homeroom-pill">${esc(t.homeroom_classes)}</span>`:"-"}</td><td><div class="row-actions"><button class="mini-btn" data-schedule="${esc(t.id)}">Jadwal</button><button class="mini-btn" data-edit="${esc(t.id)}">Edit</button></div></td></tr>`).join("");$("teacherCards").innerHTML=slice.map(t=>`<article class="teacher-card"><div class="top"><div><h4>${esc(t.full_name)}</h4><p>Kode ${esc(t.teacher_code ?? "-")} · ${esc(t.employment_status || "Status belum diisi")}</p></div><span class="workload-pill">${Number(t.teaching_slots_per_week||0)} slot</span></div><div class="teacher-meta"><div><b>NIP</b><br>${esc(t.nip || "-")}</div><div><b>NUPTK</b><br>${esc(t.nuptk || "-")}</div><div><b>Wali Kelas</b><br>${esc(t.homeroom_classes || "-")}</div><div><b>Status</b><br>${t.is_active?"Aktif":"Nonaktif"}</div></div><div class="row-actions" style="margin-top:10px"><button class="mini-btn" data-schedule="${esc(t.id)}">Lihat Jadwal</button><button class="mini-btn" data-edit="${esc(t.id)}">Edit</button></div></article>`).join("");}$("tableInfo").textContent=`${rows.length} guru · Halaman ${page} dari ${pages}`;$("prevBtn").disabled=page<=1;$("nextBtn").disabled=page>=pages;document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>openEdit(b.dataset.edit)));document.querySelectorAll("[data-schedule]").forEach(b=>b.addEventListener("click",()=>openSchedule(b.dataset.schedule)));}
function resetForm(){$("teacherForm").reset();$("teacherId").value="";$("isActive").value="true";$("formMessage").textContent="";}
function openAdd(){resetForm();$("modalTitle").textContent="Tambah Guru";const maxCode=Math.max(0,...teachers.map(t=>Number(t.teacher_code||0)));$("teacherCode").value=maxCode+1;$("teacherModal").classList.remove("hidden");}
function openEdit(id){const t=teachers.find(x=>x.id===id);if(!t) return;resetForm();$("modalTitle").textContent="Edit Data Guru";$("teacherId").value=t.id;$("teacherCode").value=t.teacher_code ?? "";$("fullName").value=t.full_name || "";$("nip").value=t.nip || "";$("nuptk").value=t.nuptk || "";$("gender").value=t.gender || "";$("phone").value=t.phone || "";$("email").value=t.email || "";$("employmentStatus").value=t.employment_status || "";$("isActive").value=String(!!t.is_active);$("teacherModal").classList.remove("hidden");}
function closeTeacherModal(){$("teacherModal").classList.add("hidden");}
async function restWrite(path,method,body,prefer="return=representation"){const session=await api.auth.getSession();if(!session?.access_token) throw new Error("Sesi login tidak ditemukan.");const cfg=window.SIMANIS_CONFIG;const res=await fetch(`${cfg.SUPABASE_URL.replace(/\/$/,"")}/rest/v1/${path}`,{method,headers:{apikey:cfg.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json",Prefer:prefer},body:body===undefined?undefined:JSON.stringify(body)});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!res.ok) throw new Error(data?.message||data?.error||text||`HTTP ${res.status}`);return data;}
async function saveTeacher(e){e.preventDefault();const btn=$("saveTeacherBtn");const id=$("teacherId").value;const payload={teacher_code:$("teacherCode").value?Number($("teacherCode").value):null,full_name:$("fullName").value.trim(),nip:$("nip").value.trim()||null,nuptk:$("nuptk").value.trim()||null,gender:$("gender").value||null,phone:$("phone").value.trim()||null,email:$("email").value.trim()||null,employment_status:$("employmentStatus").value.trim()||null,is_active:$("isActive").value==="true"};if(!payload.full_name){$("formMessage").textContent="Nama guru wajib diisi.";return;}btn.disabled=true;btn.textContent="Menyimpan...";$("formMessage").textContent="";try{if(id){await restWrite(`teachers?id=eq.${encodeURIComponent(id)}`,"PATCH",payload);}else{await restWrite("teachers","POST",payload);}closeTeacherModal();await loadTeachers();}catch(err){$("formMessage").textContent="Gagal menyimpan: "+err.message;}finally{btn.disabled=false;btn.textContent="Simpan";}}
async function openSchedule(id){const t=teachers.find(x=>x.id===id);if(!t) return;$("scheduleTitle").textContent=`Jadwal — ${t.full_name}`;$("scheduleList").innerHTML='<div class="placeholder">Memuat jadwal...</div>';$("scheduleModal").classList.remove("hidden");try{const data=await api.db.select("v_schedule_detail",`select=hari,jam,start_time,end_time,kelas,mata_pelajaran,urutan_jam&kode_guru=eq.${encodeURIComponent(t.teacher_code)}&tahun_pelajaran=eq.2026/2027&semester=eq.GANJIL`) || [];data.sort((a,b)=>dayOrder(a.hari)-dayOrder(b.hari) || Number(a.urutan_jam)-Number(b.urutan_jam));if(!data.length){$("scheduleList").innerHTML='<div class="placeholder">Guru ini belum memiliki jadwal mengajar.</div>';return;}$("scheduleList").innerHTML=data.map(s=>`<div class="schedule-row"><div class="day">${esc(s.hari)}</div><div class="slot">Jam ${esc(s.jam)}<br>${String(s.start_time).slice(0,5)}–${String(s.end_time).slice(0,5)}</div><div><strong>${esc(s.mata_pelajaran)}</strong><small>${esc(s.kelas)}</small></div></div>`).join("");}catch(err){$("scheduleList").innerHTML=`<div class="placeholder">Jadwal gagal dimuat: ${esc(err.message)}</div>`;}}
$("searchInput").addEventListener("input",()=>{page=1;render();});$("statusFilter").addEventListener("change",()=>{page=1;render();});$("workloadFilter").addEventListener("change",()=>{page=1;render();});$("prevBtn").addEventListener("click",()=>{page--;render();window.scrollTo({top:0,behavior:"smooth"});});$("nextBtn").addEventListener("click",()=>{page++;render();window.scrollTo({top:0,behavior:"smooth"});});$("addTeacherBtn").addEventListener("click",openAdd);$("closeTeacherModal").addEventListener("click",closeTeacherModal);$("cancelTeacherBtn").addEventListener("click",closeTeacherModal);$("teacherForm").addEventListener("submit",saveTeacher);$("closeScheduleModal").addEventListener("click",()=>$("scheduleModal").classList.add("hidden"));$("teacherModal").addEventListener("click",e=>{if(e.target===$("teacherModal"))closeTeacherModal();});$("scheduleModal").addEventListener("click",e=>{if(e.target===$("scheduleModal"))$("scheduleModal").classList.add("hidden");});
(async function boot(){try{api=await window.simanisReady;const session=await api.auth.getSession();if(!session){location.replace("index.html");return}const user=await api.auth.getUser();if(!user){location.replace("index.html");return}profile=await loadProfile(user);$("sideUserName").textContent=profile.full_name||user.email||"Pengguna";$("sideUserRole").textContent=formatRole(profile.role);$("headerUser").textContent=profile.full_name||user.email||"Pengguna";$("currentDate").textContent=localDateID();await loadMenu();await loadTeachers();$("logoutBtn").addEventListener("click",async()=>{await api.auth.signOut();location.replace("index.html");});}catch(err){console.error(err);alert("Data Guru gagal dimuat: "+(err.message||err));}finally{$("loading").classList.add("hidden");}})();
