const $ = (id) => document.getElementById(id);
let api, profile;
let classes = [];
let teachers = [];
let activeAcademicYearId = null;

function esc(s){return String(s ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function formatRole(role){return (role || "-").replaceAll("_"," ");}
function localDateID(){return new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());}
function routeFor(code){
  if(code==="DASHBOARD") return "dashboard.html";
  if(code==="ADMINISTRASI_KEPALA") return "administrasi.html";
  if(code==="DATA_SISWA") return "siswa.html";
  if(code==="DATA_GURU") return "guru.html";
  if(code==="KELAS") return "kelas.html";
  return "#";
}
async function loadProfile(user){const rows=await api.db.select("profiles",`select=id,full_name,role,is_active&id=eq.${encodeURIComponent(user.id)}&limit=1`);const p=rows?.[0];if(!p) throw new Error("Profil pengguna tidak ditemukan.");if(!p.is_active) throw new Error("Akun SIMANIS tidak aktif.");return p;}
async function loadMenu(){const modules=await api.db.rpc("get_my_modules",{});$("sidebarMenu").innerHTML=(modules||[]).map(m=>`<a href="${routeFor(m.code)}" class="nav-item ${m.code==="KELAS"?"active":""}"><span class="nav-dot"></span><span>${esc(m.name)}</span></a>`).join("");document.querySelectorAll('.nav-item[href="#"]').forEach(a=>a.addEventListener("click",e=>{e.preventDefault();alert(`Modul "${a.textContent.trim()}" akan diaktifkan bertahap.`);}));}
async function loadMaster(){const [teacherRows,yearRows]=await Promise.all([api.db.select("teachers","select=id,full_name,is_active&is_active=eq.true&order=full_name.asc"),api.db.select("academic_years","select=id,name,is_active&is_active=eq.true&limit=1")]);teachers=teacherRows||[];activeAcademicYearId=yearRows?.[0]?.id||null;$("homeroomTeacher").insertAdjacentHTML("beforeend",teachers.map(t=>`<option value="${esc(t.id)}">${esc(t.full_name)}</option>`).join(""));}
async function loadClasses(){classes=await api.db.select("v_classes_current","select=*&order=grade_level.asc,name.asc")||[];renderStats();render();}
function renderStats(){const active=classes.filter(c=>c.is_active);$("statClasses").textContent=active.length;$("statStudents").textContent=active.reduce((n,c)=>n+Number(c.active_students||0),0);$("statHomeroom").textContent=active.filter(c=>c.homeroom_teacher_id).length;$("statSlots").textContent=active.reduce((n,c)=>n+Number(c.schedule_slots_per_week||0),0);}
function filtered(){const q=$("searchInput").value.trim().toLowerCase();const grade=$("gradeFilter").value;const st=$("statusFilter").value;return classes.filter(c=>{const hay=`${c.name||""} ${c.major||""} ${c.homeroom_teacher||""}`.toLowerCase();const okQ=!q||hay.includes(q);const okGrade=!grade||String(c.grade_level)===grade;const okStatus=st==="SEMUA"||(st==="AKTIF"&&c.is_active)||(st==="NONAKTIF"&&!c.is_active);return okQ&&okGrade&&okStatus;});}
function gradeLabel(n){return Number(n)===10?"X":Number(n)===11?"XI":"XII";}
function render(){const rows=filtered();if(!rows.length){$("classCards").innerHTML='<div class="empty-state">Tidak ada kelas yang cocok.</div>';return;}$("classCards").innerHTML=rows.map(c=>`<article class="class-card"><div class="class-card-head"><div><h3>${esc(c.name)}</h3><p>${esc(c.homeroom_teacher||"Wali kelas belum ditentukan")}</p></div><span class="grade-pill ${c.is_active?"":"status-off"}">${c.is_active?`Kelas ${gradeLabel(c.grade_level)}`:"Nonaktif"}</span></div><div class="class-meta"><div><b>Siswa</b><br>${Number(c.active_students||0)}</div><div><b>Jurusan</b><br>${esc(c.major||"-")}</div><div><b>Slot/Minggu</b><br>${Number(c.schedule_slots_per_week||0)}</div><div><b>TA</b><br>${esc(c.academic_year||"-")}</div></div><div class="class-actions"><button class="mini-btn" data-edit="${esc(c.id)}">Edit</button><button class="mini-btn" data-students="${esc(c.id)}">Lihat Siswa</button></div></article>`).join("");document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>openEdit(b.dataset.edit)));document.querySelectorAll("[data-students]").forEach(b=>b.addEventListener("click",()=>location.href=`siswa.html?class_id=${encodeURIComponent(b.dataset.students)}`));}
function resetForm(){$("classForm").reset();$("classId").value="";$("gradeLevel").value="10";$("isActive").value="true";$("formMessage").textContent="";}
function openAdd(){resetForm();$("modalTitle").textContent="Tambah Kelas";$("classModal").classList.remove("hidden");}
function openEdit(id){const c=classes.find(x=>x.id===id);if(!c)return;resetForm();$("modalTitle").textContent="Edit Kelas / Rombel";$("classId").value=c.id;$("className").value=c.name||"";$("gradeLevel").value=String(c.grade_level||10);$("major").value=c.major||"";$("homeroomTeacher").value=c.homeroom_teacher_id||"";$("isActive").value=String(!!c.is_active);$("classModal").classList.remove("hidden");}
function closeModal(){$("classModal").classList.add("hidden");}
async function restWrite(path,method,body,prefer="return=representation"){const session=await api.auth.getSession();if(!session?.access_token)throw new Error("Sesi login tidak ditemukan.");const cfg=window.SIMANIS_CONFIG;const res=await fetch(`${cfg.SUPABASE_URL.replace(/\/$/,"")}/rest/v1/${path}`,{method,headers:{apikey:cfg.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json",Prefer:prefer},body:body===undefined?undefined:JSON.stringify(body)});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!res.ok)throw new Error(data?.message||data?.error||text||`HTTP ${res.status}`);return data;}
async function saveClass(e){e.preventDefault();const btn=$("saveBtn");const id=$("classId").value;const payload={academic_year_id:activeAcademicYearId,name:$("className").value.trim(),grade_level:Number($("gradeLevel").value),major:$("major").value.trim()||null,homeroom_teacher_id:$("homeroomTeacher").value||null,is_active:$("isActive").value==="true"};if(!payload.name){$("formMessage").textContent="Nama kelas wajib diisi.";return;}if(!payload.academic_year_id){$("formMessage").textContent="Tahun pelajaran aktif tidak ditemukan.";return;}btn.disabled=true;btn.textContent="Menyimpan...";$("formMessage").textContent="";try{if(id)await restWrite(`classes?id=eq.${encodeURIComponent(id)}`,"PATCH",payload);else await restWrite("classes","POST",payload);closeModal();await loadClasses();}catch(err){$("formMessage").textContent="Gagal menyimpan: "+err.message;}finally{btn.disabled=false;btn.textContent="Simpan";}}
$("searchInput").addEventListener("input",render);$("gradeFilter").addEventListener("change",render);$("statusFilter").addEventListener("change",render);$("addClassBtn").addEventListener("click",openAdd);$("closeModalBtn").addEventListener("click",closeModal);$("cancelBtn").addEventListener("click",closeModal);$("classForm").addEventListener("submit",saveClass);$("classModal").addEventListener("click",e=>{if(e.target===$("classModal"))closeModal();});
(async function boot(){try{api=await window.simanisReady;const session=await api.auth.getSession();if(!session){location.replace("index.html");return}const user=await api.auth.getUser();if(!user){location.replace("index.html");return}profile=await loadProfile(user);$("sideUserName").textContent=profile.full_name||user.email||"Pengguna";$("sideUserRole").textContent=formatRole(profile.role);$("headerUser").textContent=profile.full_name||user.email||"Pengguna";$("currentDate").textContent=localDateID();await Promise.all([loadMenu(),loadMaster()]);await loadClasses();$("logoutBtn").addEventListener("click",async()=>{await api.auth.signOut();location.replace("index.html");});}catch(err){console.error(err);alert("Kelas / Rombel gagal dimuat: "+(err.message||err));}finally{$("loading").classList.add("hidden");}})();
